# fishros deploy tool 
# 所有的操作都在工程目录进行
# os / docker 
mode: os
env: os
name: ros2doc
tag: foxy
parallel: true
stage:
  prepare:
    - echo "prepare"
    - mkdir -p /root/ros2/master/doc/
    - mkdir -p /root/ros2/dev/doc/
  start:
    - rm -rf /root/ros2/master/doc/*
    - rm -rf /root/ros2/dev/doc/*
  end:
    - cp -r * /root/ros2/master/doc/
    - cp -r * /root/ros2/dev/doc/
# 超时
timeout: 200
